### PR TITLE
Fix/general improvements

### PR DESCRIPTION
**Pull request by DMC09**

### CODE REVIEW

**Comment by DMC09** [comment]
@CodiumAI-Agent /describe

**Comment by DMC09** [comment]
@CodiumAI-Agent /describe

**Comment by DMC09** [comment]
@CodiumAI-Agent /describe

**Comment by DMC09** [comment]
@CodiumAI-Agent /describe

**Comment by coditamar** [comment]
> @CodiumAI-Agent /describe

this command users the PR-Agent hosted by CodiumAI.
if you want to use a GitHub Action that users your keys, you need to call the commands directly, e.g.
`/describe`

**Comment by coditamar** [comment]
the `/describe` is failing.
https://github.com/DMC09/grocer-app-ui/actions/runs/6102456258/job/16560969064
it seems to reach some RateLimit:
`openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.`

**Comment by DMC09** [comment]
> 

I don't understand the usage stuff for the open AI. It looks like I haven't used anything according to the API Dashboard chart. 


Screenshot 2023-09-06 at 4 19 12 PM

**Comment by DMC09** [comment]
Okay I looked it up it's because the per minute limit is 3 so of course it won't let me do it.

**Comment by DMC09** [comment]
@CodiumAI-Agent /describe

**Comment by DMC09** [comment]
Hmm well this is odd. I tried describe with and without tagging the ai agent. 

here is the build for when I comment without tagging 

https://github.com/DMC09/grocer-app-ui/actions/runs/6102632724

Here is the build for when I do tag it 

https://github.com/DMC09/grocer-app-ui/actions/runs/6102673811


But another odd thing is that when you look at those runs and then you look at the WorkFlow File the .yml is outdated. I doesn't even include 
  CONFIG.MODEL: gpt-3.5-turbo 
  or the permissions.
  
  Why does it try to use an old .yml file both times?
  
  How can I get it to use the one in the this branch?

**Comment by DMC09** [comment]
I also added 10$ to my account 

Screenshot 2023-09-06 at 4 41 02 PM

**Comment by coditamar** [comment]
@CodiumAI-Agent /describe -c

**Comment by DMC09** [comment]
@coditamar , Any thoughts on this? Is there a bug with the PR agent right now?

**Comment by coditamar** [comment]
@CodiumAI-Agent /describe --pr_description=publish_description_as_comment=true

**Comment by coditamar** [comment]
@CodiumAI-Agent /describe --pr_description.publish_description_as_comment=true

**Comment by okotek** [comment]
@CodiumAI-Agent /describe --pr_description.publish_description_as_comment=true

**Comment by coditamar** [comment]
/describe --pr_description.publish_description_as_comment=true

**Comment by coditamar** [comment]
@DMC09 , for your own GitHub Action configuration,
You are missing the write permissions here:
https://github.com/DMC09/grocer-app-ui/blob/main/.github/workflows/pr_agent.yml
`permissions:
  issues: write
  pull-requests: write`

And as for the free yet limited CodiumAI-Agent, you can see that it is working now.

**Comment by DMC09** [comment]
@coditamar  Okay so I have the updated .yml file in this PR so I guess I have to merge it in then after that It should be good right?

So just for clarification I shouldn't have to tag the ai agent to use the commands right? I can just use the commands and comment those.

**Comment by coditamar** [comment]
> @coditamar Okay so I have the updated .yml file in this PR so I guess I have to merge it in then after that It should be good right?
> 
> So just for clarification I shouldn't have to tag the ai agent to use the commands right? I can just use the commands and comment those.

once you workflow is set up correctly, and you have sufficient funds in OpenAI API, then you can start using the `/commands` with out tagging CodiumAI-Agent, right.

**Pull request merged**
